# Generated by Django 4.0.6 on 2022-07-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcation',
            name='currency_type',
            field=models.CharField(default='USD', max_length=4),
            preserve_default=False,
        ),
    ]
