# Generated by Django 4.0.6 on 2022-07-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=models.CharField(max_length=200), max_length=50),
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='balance',
            name='pay_pin',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Transcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='main.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.user')),
            ],
        ),
    ]
