version: "3.9"
   
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres # addded credientials in production
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 cash.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # environment:
    #   - POSTGRES_NAME=postgres # addded credientials in production
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

